version: "3.8"

services:
  prometheus:
    build:
      context: .
      dockerfile: ./docker/prometheus/Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: ./golang-htmx-crud
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/posgresql/data

volumes:
  db-volume:
