---
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: [localhost:9090]
  - job_name: app
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: [host.docker.internal:42069]
