linters:
  enable-all: true
  disable:
    - gci # not using gci
    - wrapcheck # conflict with Echo
    - err113 # want to Errorf without wrapping
    - exhaustruct # because can't SomeStruct{}
    - depguard # don't want to clean main now
    - execinquery # Deprecated
    - gomnd # Deprecated
