linters:
  enable-all: true
  disable:
    - gci # not using gci
    - wrapcheck # conflict with Echo
    - err113 # want to Errorf wthout wrapping
    - exhaustruct # because can't SomeStruct{}
    - depguard # don't want to clean main now
    - execinquery # Deprecated
    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - gomnd # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated
